apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: carrier-vaultkubenertes-job
  namespace: carrier-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: carrier-vaultkubenertes-job
  chart:
    git: git@github.com:johnhomantaring/bevel.git
    ref: local
    path: platforms/hyperledger-fabric/charts/vault_kubernetes
  values:
    metadata:
      name: carrier
      component_type: peer
      namespace: carrier-net    
      images:
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0

    vault:
      reviewer_service: vault-reviewer
      role: vault-role
      address: http://ad2b3256948824b8ea29b1b94712af55-1558072461.ap-southeast-1.elb.amazonaws.com:8200
      authpath: devcarrier-net-auth
      policy: vault-crypto-peer-carrier-net-ro
      secret_path: secretsv2
      serviceaccountname: vault-auth
      imagesecretname: regcred
    
    k8s:
      kubernetes_url: https://20D0964F80BFF986ED0714500043E196.gr7.ap-southeast-1.eks.amazonaws.com
