apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: anchorpeer-allchannel-wholesaler
  namespace: wholesaler-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: anchorpeer-allchannel-wholesaler
  chart:
    git: git@github.com:johnhomantaring/bevel.git
    ref: local
    path: platforms/hyperledger-fabric/charts/anchorpeer
  values:
    metadata:
      namespace: wholesaler-net
      images:
        fabrictools: hyperledger/fabric-tools:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0

    peer:
      name: peer0
      address: peer0.wholesaler-net:7051
      localmspid: wholesalerMSP
      loglevel: debug
      tlsstatus: true

    vault:
      role: vault-role
      address: http://a50fb759de7a74c7380c5e1e627f2212-248118612.ap-southeast-1.elb.amazonaws.com:8201
      authpath: devwholesaler-net-auth
      adminsecretprefix: secretsv2/data/crypto/peerOrganizations/wholesaler-net/users/admin
      orderersecretprefix: secretsv2/data/crypto/peerOrganizations/wholesaler-net/orderer
      serviceaccountname: vault-auth
      imagesecretname: regcred

    channel:
      name: allchannel      
    orderer:
      address: orderer1.supplychain-net:7050
    anchorstx: |-
      CsECChgKFggCGgYIzJ+vlwYiCmFsbGNoYW5uZWwSpAIKoQIKCmFsbGNoYW5uZWwSZhJkCgtBcHBs
      aWNhdGlvbhJVCAESUQoNd2hvbGVzYWxlck1TUBJAGgcKA01TUBIAIgsKB1JlYWRlcnMSACILCgdX
      cml0ZXJzEgAiCgoGQWRtaW5zEgAiDwoLRW5kb3JzZW1lbnQSABqqARKnAQoLQXBwbGljYXRpb24S
      lwEIARKSAQoNd2hvbGVzYWxlck1TUBKAAQgBGjQKC0FuY2hvclBlZXJzEiUSGwoZChRwZWVyMC53
      aG9sZXNhbGVyLW5ldBCLNxoGQWRtaW5zGgcKA01TUBIAIgsKB1JlYWRlcnMSACILCgdXcml0ZXJz
      EgAiCgoGQWRtaW5zEgAiDwoLRW5kb3JzZW1lbnQSACoGQWRtaW5z

