apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: supplychain-orderer1
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: supplychain-orderer1
  chart:
    git: git@github.com:johnhomantaring/bevel.git
    ref: local
    path: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: supplychain-net
      images:
        orderer: hyperledger/fabric-orderer:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    annotations:  
      service:
        - example1: example2
      pvc:
      deployment:
    orderer:
      name: orderer1
      loglevel: info
      localmspid: supplychainMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://afa8761a6902d4eed83106ebd15d7aec-1934446345.ap-southeast-1.elb.amazonaws.com:8200
      role: vault-role
      authpath: devsupplychain-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/supplychain-net/orderers/orderer1.supplychain-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: develop.local.com

    genesis: |-
      CiIaIOiZ7peZfhr/n/fxsMXcufeXBqYR7hsLM8c0KKodDQ3lEppeCpdeCpReCngKWggBEAEaBgjd
      9OKWBiIKc3lzY2hhbm5lbCpANzA4NGJmMGNhYWVkMzdkYjQ0ZWJlNTcyN2U5MjA1ZDkwZWFhZDkx
      NWVmNzQ3MTlhNDMyN2NlZDFkNTM0ZWRmNRIaEhhreA1Z19JorrzCIXzfGtdsElT9A2bCtAQSl10K
      lF0SkV0SkSsKB09yZGVyZXIShSsSyhYKDnN1cHBseWNoYWluTVNQErcWGsMUCgNNU1ASuxQSsBQS
      rRQKDnN1cHBseWNoYWluTVNQEvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNBREND
      QWFhZ0F3SUJBZ0lVUWRkZzJpZFRCRVY2cHdoS0R1N2d0YVg2UVJNd0NnWUlLb1pJemowRUF3SXcK
      WGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndi
      SGxqYUdGcGJpMXVaWFF3CkhoY05Nakl3TnpJeE1ESXhOVEU1V2hjTk1qVXdOVEV3TURJeE5URTVX
      akJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhE
      QVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1NRW1OaExuTjFj
      SEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VIQTBJQUJGSHV6
      Z1lWNjRvWEY3MVVubm45V1k5Tng1bmFIWFprU1IxN3hKbmhYdGFhSTR3ZmpwcHIKU1JOalJWNDVU
      ankyWmFmb3JBNWx2T0JLSTluNXlIQWR2WXlqUWpCQU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpE
      Z1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCVGszcnRQY0pVYmZOdXlhZ1Yzem5aUU9P
      bWI2akFLCkJnZ3Foa2pPUFFRREFnTklBREJGQWlBZ3VlTzZYWjVidURuUThWaENNdy83blFZUE5G
      TnVXSXlqSmkwQjlMcWMKRmdJaEFJYjExbnF3VmZoSkFXSWFldi9mWi90YVBpQU5yUldwTHNud1B6
      WXh6aTRDCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIqIILS0tLS1CRUdJTiBDRVJUSUZJQ0FU
      RS0tLS0tCk1JSUM0VENDQW9pZ0F3SUJBZ0lVVUxDQnVWRHlUQnV0QnZiVkZDOTNCUGlNWGdJd0Nn
      WUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJq
      RVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZR
      UUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nakl3TnpJeE1ESXlNVEF3V2hjTk1q
      TXdOekl4TURJeU5qQXdXakJzTVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5U
      QXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVE0dwpEQVlEVlFRTEV3
      VmhaRzFwYmpFZU1Cd0dBMVVFQXd3VlFXUnRhVzVBYzNWd2NHeDVZMmhoYVc0dGJtVjBNRmt3CkV3
      WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFTW5jM2NJMDVtazk2YjIrWjVabmhHb1U4WklU
      alZzbTcKVGhaN00vRnNLdGU0a1dPaHFBbnMxWHZqWklzY1pvaEM1ZE5xUVBjRU1zVUZtUmhibnQy
      eUhhT0NBUlF3Z2dFUQpNQTRHQTFVZER3RUIvd1FFQXdJSGdEQU1CZ05WSFJNQkFmOEVBakFBTUIw
      R0ExVWREZ1FXQkJSS21CMmt0anA0CjZBaWxUczNEV0JSYldLTHRCREFmQmdOVkhTTUVHREFXZ0JU
      azNydFBjSlViZk51eWFnVjN6blpRT09tYjZqQWsKQmdOVkhSRUVIVEFiZ2hsallTMTBiMjlzY3kw
      M05UVm1PV1ExWWpkakxXNDRZakp6TUlHSkJnZ3FBd1FGQmdjSQpBUVI5ZXlKaGRIUnljeUk2ZXlK
      aFltRmpMbWx1YVhRaU9pSjBjblZsSWl3aVlXUnRhVzRpT2lKMGNuVmxJaXdpCmFHWXVRV1ptYVd4
      cFlYUnBiMjRpT2lJaUxDSm9aaTVGYm5KdmJHeHRaVzUwU1VRaU9pSkJaRzFwYmtCemRYQncKYkhs
      amFHRnBiaTF1WlhRaUxDSm9aaTVVZVhCbElqb2lZV1J0YVc0aWZYMHdDZ1lJS29aSXpqMEVBd0lE
      UndBdwpSQUlnUzNPOTIxRUJlTmtaR0dxMWFtajhlSy9kbk1vLzlNY2VJNjNDZ1ZrUEppWUNJQzds
      bE1aTW56KzN3YU8wCkhxMVE4OGlxZFhyeUo4QW5UQlVsYUp5Y1JjWWMKLS0tLS1FTkQgQ0VSVElG
      SUNBVEUtLS0tLQpCDgoEU0hBMhIGU0hBMjU2SvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t
      Ck1JSUNBRENDQWFhZ0F3SUJBZ0lVUWRkZzJpZFRCRVY2cHdoS0R1N2d0YVg2UVJNd0NnWUlLb1pJ
      emowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBH
      QTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpq
      WVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nakl3TnpJeE1ESXhOVEU1V2hjTk1qVXdOVEV3
      TURJeE5URTVXakJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3
      RFFZRFZRUUhEQVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1N
      RW1OaExuTjFjSEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VI
      QTBJQUJGSHV6Z1lWNjRvWEY3MVVubm45V1k5Tng1bmFIWFprU1IxN3hKbmhYdGFhSTR3ZmpwcHIK
      U1JOalJWNDVUankyWmFmb3JBNWx2T0JLSTluNXlIQWR2WXlqUWpCQU1BOEdBMVVkRXdFQi93UUZN
      QU1CQWY4dwpEZ1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCVGszcnRQY0pVYmZOdXlh
      Z1Yzem5aUU9PbWI2akFLCkJnZ3Foa2pPUFFRREFnTklBREJGQWlBZ3VlTzZYWjVidURuUThWaENN
      dy83blFZUE5GTnVXSXlqSmkwQjlMcWMKRmdJaEFJYjExbnF3VmZoSkFXSWFldi9mWi90YVBpQU5y
      UldwTHNud1B6WXh6aTRDCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiOAoGQWRt
      aW5zEi4SJAgBEiASCBIGCAESAggAGhQSEgoOc3VwcGx5Y2hhaW5NU1AQARoGQWRtaW5zIjsKC0Vu
      ZG9yc2VtZW50EiwSIggBEh4SCBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5NU1AaBkFkbWlucyI3
      CgdSZWFkZXJzEiwSIggBEh4SCBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5NU1AaBkFkbWlucyI3
      CgdXcml0ZXJzEiwSIggBEh4SCBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5NU1AaBkFkbWlucyoG
      QWRtaW5zGh8KE0NoYW5uZWxSZXN0cmljdGlvbnMSCBoGQWRtaW5zGiQKDENhcGFiaWxpdGllcxIU
      EgoKCAoEVjJfMBIAGgZBZG1pbnMaihIKDUNvbnNlbnN1c1R5cGUS+BES7REKCGV0Y2RyYWZ0EuAR
      CskRChhvcmRlcmVyMS5zdXBwbHljaGFpbi1uZXQQijca0wgtLS0tLUJFR0lOIENFUlRJRklDQVRF
      LS0tLS0KTUlJREF6Q0NBcW1nQXdJQkFnSVVNMjBrb09ibjhSTGNZT1JzZGExdTd4ZzBGczh3Q2dZ
      SUtvWkl6ajBFQXdJdwpYakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpF
      UE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1Sc3dHUVlEVlFR
      RERCSmpZUzV6ZFhCd2JIbGphR0ZwYmkxdVpYUXcKSGhjTk1qSXdOekl4TURJeU1UQXdXaGNOTWpN
      d056SXhNREl5TmpBd1dqQnhNUXN3Q1FZRFZRUUdFd0pIUWpFYgpNQmtHQTFVRUJ4TVNOVEV1TlRB
      dkxUQXVNVE12VEc5dVpHOXVNUkF3RGdZRFZRUUtFd2RQY21SbGNtVnlNUkF3CkRnWURWUVFMRXdk
      dmNtUmxjbVZ5TVNFd0h3WURWUVFERXhodmNtUmxjbVZ5TVM1emRYQndiSGxqYUdGcGJpMXUKWlhR
      d1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFTQXA5dFk5SWFTMFF4SitHNndqRXp2
      RTZBVAowMGliTGZmNWdQVFF6NzNEd2tsL3pIcHp4SndGZ3ovalR2QTdmQWtPdnQwTWxZeGxYZis0
      NkdwQktWNEZvNElCCk1EQ0NBU3d3RGdZRFZSMFBBUUgvQkFRREFnT29NQjBHQTFVZEpRUVdNQlFH
      Q0NzR0FRVUZCd01CQmdnckJnRUYKQlFjREFqQU1CZ05WSFJNQkFmOEVBakFBTUIwR0ExVWREZ1FX
      QkJUbXEvUWZMNmhtU1lHbURJRVNLbEpkNkIyUApwVEFmQmdOVkhTTUVHREFXZ0JUazNydFBjSlVi
      Zk51eWFnVjN6blpRT09tYjZqQS9CZ05WSFJFRU9EQTJnaGh2CmNtUmxjbVZ5TVM1emRYQndiSGxq
      YUdGcGJpMXVaWFNDR205eVpHVnlaWEl4TG1SbGRtVnNiM0F1Ykc5allXd3UKWTI5dE1Hd0dDQ29E
      QkFVR0J3Z0JCR0I3SW1GMGRISnpJanA3SW1obUxrRm1abWxzYVdGMGFXOXVJam9pSWl3aQphR1l1
      Ulc1eWIyeHNiV1Z1ZEVsRUlqb2liM0prWlhKbGNqRXVjM1Z3Y0d4NVkyaGhhVzR0Ym1WMElpd2lh
      R1l1ClZIbHdaU0k2SW05eVpHVnlaWElpZlgwd0NnWUlLb1pJemowRUF3SURTQUF3UlFJaEFNTjJY
      R1JnMHc3akFFOXMKT2ZWK2RJeVQxUW5KK3E4OGx6dFZTR1Qya09tWkFpQUhweGhicVJWMEJCZ0NR
      R1RDbkh3WStxRG5ra1o5dFNSawpTUGtJdHVXTUx3PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0t
      LQoi0wgtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJREF6Q0NBcW1nQXdJQkFnSVVNMjBr
      b09ibjhSTGNZT1JzZGExdTd4ZzBGczh3Q2dZSUtvWkl6ajBFQXdJdwpYakVMTUFrR0ExVUVCaE1D
      UjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lE
      VlFRS0RBZFBjbVJsY21WeU1Sc3dHUVlEVlFRRERCSmpZUzV6ZFhCd2JIbGphR0ZwYmkxdVpYUXcK
      SGhjTk1qSXdOekl4TURJeU1UQXdXaGNOTWpNd056SXhNREl5TmpBd1dqQnhNUXN3Q1FZRFZRUUdF
      d0pIUWpFYgpNQmtHQTFVRUJ4TVNOVEV1TlRBdkxUQXVNVE12VEc5dVpHOXVNUkF3RGdZRFZRUUtF
      d2RQY21SbGNtVnlNUkF3CkRnWURWUVFMRXdkdmNtUmxjbVZ5TVNFd0h3WURWUVFERXhodmNtUmxj
      bVZ5TVM1emRYQndiSGxqYUdGcGJpMXUKWlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJC
      d05DQUFTQXA5dFk5SWFTMFF4SitHNndqRXp2RTZBVAowMGliTGZmNWdQVFF6NzNEd2tsL3pIcHp4
      SndGZ3ovalR2QTdmQWtPdnQwTWxZeGxYZis0NkdwQktWNEZvNElCCk1EQ0NBU3d3RGdZRFZSMFBB
      UUgvQkFRREFnT29NQjBHQTFVZEpRUVdNQlFHQ0NzR0FRVUZCd01CQmdnckJnRUYKQlFjREFqQU1C
      Z05WSFJNQkFmOEVBakFBTUIwR0ExVWREZ1FXQkJUbXEvUWZMNmhtU1lHbURJRVNLbEpkNkIyUApw
      VEFmQmdOVkhTTUVHREFXZ0JUazNydFBjSlViZk51eWFnVjN6blpRT09tYjZqQS9CZ05WSFJFRU9E
      QTJnaGh2CmNtUmxjbVZ5TVM1emRYQndiSGxqYUdGcGJpMXVaWFNDR205eVpHVnlaWEl4TG1SbGRt
      VnNiM0F1Ykc5allXd3UKWTI5dE1Hd0dDQ29EQkFVR0J3Z0JCR0I3SW1GMGRISnpJanA3SW1obUxr
      Rm1abWxzYVdGMGFXOXVJam9pSWl3aQphR1l1Ulc1eWIyeHNiV1Z1ZEVsRUlqb2liM0prWlhKbGNq
      RXVjM1Z3Y0d4NVkyaGhhVzR0Ym1WMElpd2lhR1l1ClZIbHdaU0k2SW05eVpHVnlaWElpZlgwd0Nn
      WUlLb1pJemowRUF3SURTQUF3UlFJaEFNTjJYR1JnMHc3akFFOXMKT2ZWK2RJeVQxUW5KK3E4OGx6
      dFZTR1Qya09tWkFpQUhweGhicVJWMEJCZ0NRR1RDbkh3WStxRG5ra1o5dFNSawpTUGtJdHVXTUx3
      PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoSEgoFNTAwbXMQChgBIAUogICACBoGQWRtaW5z
      GiIKCUJhdGNoU2l6ZRIVEgsIChCAgIAxGICAQBoGQWRtaW5zGh4KDEJhdGNoVGltZW91dBIOEgQK
      AjJzGgZBZG1pbnMiKgoPQmxvY2tWYWxpZGF0aW9uEhcSDQgDEgkKB1dyaXRlcnMaBkFkbWlucyIi
      CgdSZWFkZXJzEhcSDQgDEgkKB1JlYWRlcnMaBkFkbWlucyIiCgdXcml0ZXJzEhcSDQgDEgkKB1dy
      aXRlcnMaBkFkbWlucyIiCgZBZG1pbnMSGBIOCAMSCgoGQWRtaW5zEAIaBkFkbWlucyoGQWRtaW5z
      ErkvCgtDb25zb3J0aXVtcxKpLxLeLgoVU3VwcGx5Q2hhaW5Db25zb3J0aXVtEsQuErEXCg9tYW51
      ZmFjdHVyZXJNU1ASnRcapRUKA01TUBKdFRKSFRKPFQoPbWFudWZhY3R1cmVyTVNQEoEGLS0tLS1C
      RUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNERENDQWJLZ0F3SUJBZ0lVTWxmQ1RyVTFKUEFZSjJq
      YXViSzVtcS85ekVvd0NnWUlLb1pJemowRUF3SXcKWkRFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOQmdO
      VkJBZ01CbHAxY21samFERVBNQTBHQTFVRUJ3d0dXblZ5YVdObwpNUlV3RXdZRFZRUUtEQXhOWVc1
      MVptRmpkSFZ5WlhJeEhEQWFCZ05WQkFNTUUyTmhMbTFoYm5WbVlXTjBkWEpsCmNpMXVaWFF3SGhj
      Tk1qSXdOekl4TURJeE56UXlXaGNOTWpVd05URXdNREl4TnpReVdqQmtNUXN3Q1FZRFZRUUcKRXdK
      RFNERVBNQTBHQTFVRUNBd0dXblZ5YVdOb01ROHdEUVlEVlFRSERBWmFkWEpwWTJneEZUQVRCZ05W
      QkFvTQpERTFoYm5WbVlXTjBkWEpsY2pFY01Cb0dBMVVFQXd3VFkyRXViV0Z1ZFdaaFkzUjFjbVZ5
      TFc1bGREQlpNQk1HCkJ5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEEwSUFCTUVVYjZzejJ5NThyeWsr
      MGdtMnRWRTladWZQMDhHZjVPTGEKK1UyNEt6aWw1dkR6UXNWakFVa1g2RzV1Qi9DL1FCUWdYQ3Vo
      ZGRaemlyeUlyYzkwcngyalFqQkFNQThHQTFVZApFd0VCL3dRRk1BTUJBZjh3RGdZRFZSMFBBUUgv
      QkFRREFnR21NQjBHQTFVZERnUVdCQlN4Vmd1Yml5UzJtZHlrCmFabVhEWGtDOXVhNE9EQUtCZ2dx
      aGtqT1BRUURBZ05JQURCRkFpRUE5cFRVZ2d0UzFNWURPNGxYZHNlMkRlNFkKOHdvRmoraWloNDY5
      ZkFUVkptMENJRnNhTTNWS2hpc3ByZnphRnNWVEJVaXVVclErLzJFbmpGQjQ1VzAzVFhjUgotLS0t
      LUVORCBDRVJUSUZJQ0FURS0tLS0tCiLjCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlE
      RVRDQ0FyZWdBd0lCQWdJVU1uRzlQWENMUitFRWwvMzBwcWJXakdST0hUa3dDZ1lJS29aSXpqMEVB
      d0l3ClpERUxNQWtHQTFVRUJoTUNRMGd4RHpBTkJnTlZCQWdNQmxwMWNtbGphREVQTUEwR0ExVUVC
      d3dHV25WeWFXTm8KTVJVd0V3WURWUVFLREF4TllXNTFabUZqZEhWeVpYSXhIREFhQmdOVkJBTU1F
      Mk5oTG0xaGJuVm1ZV04wZFhKbApjaTF1WlhRd0hoY05Nakl3TnpJeE1ESXlNekF3V2hjTk1qTXdO
      ekl4TURJeU9EQXdXakNCaGpFTE1Ba0dBMVVFCkJoTUNRMGd4R2pBWUJnTlZCQWNURVRRM0xqTTRM
      emd1TlRRdlduVnlhV05vTVJVd0V3WURWUVFLRXd4TllXNTEKWm1GamRIVnlaWEl4SXpBTUJnTlZC
      QXNUQldGa2JXbHVNQk1HQTFVRUN4TU1iV0Z1ZFdaaFkzUjFjbVZ5TVI4dwpIUVlEVlFRRERCWkJa
      RzFwYmtCdFlXNTFabUZqZEhWeVpYSXRibVYwTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJCnpqMERB
      UWNEUWdBRUJuL0cwcmFHNGp6aURYVTFsRTc5ZHBZakk1NUsvY2x5b0hxZU9VYmZvbVhYU0htM05K
      bnEKSDRKU3pPSSt6TlNCMFhaY2xmbG1oYzJhV3djMWlKSldRS09DQVNJd2dnRWVNQTRHQTFVZER3
      RUIvd1FFQXdJSApnREFNQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVkRGdRV0JCVDNjVFZla2Y3YkEy
      aFB1bTNBR00xRjJKMXlTVEFmCkJnTlZIU01FR0RBV2dCU3hWZ3ViaXlTMm1keWthWm1YRFhrQzl1
      YTRPREFrQmdOVkhSRUVIVEFiZ2hsallTMTAKYjI5c2N5MDJaR1E1Tm1SbU5XSTBMWEEzWm1OaU1J
      R1hCZ2dxQXdRRkJnY0lBUVNCaW5zaVlYUjBjbk1pT25zaQpZV0poWXk1cGJtbDBJam9pZEhKMVpT
      SXNJbUZrYldsdUlqb2lkSEoxWlNJc0ltaG1Ma0ZtWm1sc2FXRjBhVzl1Cklqb2liV0Z1ZFdaaFkz
      UjFjbVZ5SWl3aWFHWXVSVzV5YjJ4c2JXVnVkRWxFSWpvaVFXUnRhVzVBYldGdWRXWmgKWTNSMWNt
      VnlMVzVsZENJc0ltaG1MbFI1Y0dVaU9pSmhaRzFwYmlKOWZUQUtCZ2dxaGtqT1BRUURBZ05JQURC
      RgpBaUVBdHBUdHZEcVFsdEh2ZzFFV1A0TndaU29TZ1FmU3FTb2J0Z3N4aVFiaVFaNENJRG5rdXVS
      VTZGL1RVQXZSCjRtN2tkQVBPTFJERzR2K2JuV1k0ZHJ1VWw1bzEKLS0tLS1FTkQgQ0VSVElGSUNB
      VEUtLS0tLQpCDgoEU0hBMhIGU0hBMjU2SoEGLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1J
      SUNERENDQWJLZ0F3SUJBZ0lVTWxmQ1RyVTFKUEFZSjJqYXViSzVtcS85ekVvd0NnWUlLb1pJemow
      RUF3SXcKWkRFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOQmdOVkJBZ01CbHAxY21samFERVBNQTBHQTFV
      RUJ3d0dXblZ5YVdObwpNUlV3RXdZRFZRUUtEQXhOWVc1MVptRmpkSFZ5WlhJeEhEQWFCZ05WQkFN
      TUUyTmhMbTFoYm5WbVlXTjBkWEpsCmNpMXVaWFF3SGhjTk1qSXdOekl4TURJeE56UXlXaGNOTWpV
      d05URXdNREl4TnpReVdqQmtNUXN3Q1FZRFZRUUcKRXdKRFNERVBNQTBHQTFVRUNBd0dXblZ5YVdO
      b01ROHdEUVlEVlFRSERBWmFkWEpwWTJneEZUQVRCZ05WQkFvTQpERTFoYm5WbVlXTjBkWEpsY2pF
      Y01Cb0dBMVVFQXd3VFkyRXViV0Z1ZFdaaFkzUjFjbVZ5TFc1bGREQlpNQk1HCkJ5cUdTTTQ5QWdF
      R0NDcUdTTTQ5QXdFSEEwSUFCTUVVYjZzejJ5NThyeWsrMGdtMnRWRTladWZQMDhHZjVPTGEKK1Uy
      NEt6aWw1dkR6UXNWakFVa1g2RzV1Qi9DL1FCUWdYQ3VoZGRaemlyeUlyYzkwcngyalFqQkFNQThH
      QTFVZApFd0VCL3dRRk1BTUJBZjh3RGdZRFZSMFBBUUgvQkFRREFnR21NQjBHQTFVZERnUVdCQlN4
      Vmd1Yml5UzJtZHlrCmFabVhEWGtDOXVhNE9EQUtCZ2dxaGtqT1BRUURBZ05JQURCRkFpRUE5cFRV
      Z2d0UzFNWURPNGxYZHNlMkRlNFkKOHdvRmoraWloNDY5ZkFUVkptMENJRnNhTTNWS2hpc3ByZnph
      RnNWVEJVaXVVclErLzJFbmpGQjQ1VzAzVFhjUgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChoG
      QWRtaW5zIjgKB1dyaXRlcnMSLRIjCAESHxIIEgYIARICCAAaExIRCg9tYW51ZmFjdHVyZXJNU1Aa
      BkFkbWlucyI5CgZBZG1pbnMSLxIlCAESIRIIEgYIARICCAAaFRITCg9tYW51ZmFjdHVyZXJNU1AQ
      ARoGQWRtaW5zIjwKC0VuZG9yc2VtZW50Ei0SIwgBEh8SCBIGCAESAggAGhMSEQoPbWFudWZhY3R1
      cmVyTVNQGgZBZG1pbnMiOAoHUmVhZGVycxItEiMIARIfEggSBggBEgIIABoTEhEKD21hbnVmYWN0
      dXJlck1TUBoGQWRtaW5zKgZBZG1pbnMSshYKCmNhcnJpZXJNU1ASoxYavxQKA01TUBK3FBKsFBKp
      FAoKY2Fycmllck1TUBLpBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCK1RDQ0FaNmdB
      d0lCQWdJVVZSWGgzMEtQYjBtdkQzbWUrLysvbFZoVEErUXdDZ1lJS29aSXpqMEVBd0l3CldqRUxN
      QWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpH
      OXUKTVJBd0RnWURWUVFLREFkRFlYSnlhV1Z5TVJjd0ZRWURWUVFEREE1allTNWpZWEp5YVdWeUxX
      NWxkREFlRncweQpNakEzTWpFd01qRTVNalphRncweU5UQTFNVEF3TWpFNU1qWmFNRm94Q3pBSkJn
      TlZCQVlUQWtkQ01ROHdEUVlEClZRUUlEQVpNYjI1a2IyNHhEekFOQmdOVkJBY01Ca3h2Ym1SdmJq
      RVFNQTRHQTFVRUNnd0hRMkZ5Y21sbGNqRVgKTUJVR0ExVUVBd3dPWTJFdVkyRnljbWxsY2kxdVpY
      UXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQwpBQVR4Sk1JY2VjSWdPdHFJbDVHWTNP
      REMrb3E5R1Y4MmVUY2xqNHpmakhXNWJpWkFwWjN3SXU2WVR0WEUyRC9uCnI2OTJRWjR6NnpnREdq
      ZTFVdmFzL1hyQ28wSXdRREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTRHQTFVZER3RUIKL3dRRUF3
      SUJwakFkQmdOVkhRNEVGZ1FVS3ZsaDFkOTk5MTZ0bWROekJ5dlN5aDk5bmI0d0NnWUlLb1pJemow
      RQpBd0lEU1FBd1JnSWhBT3pXK3ZNTVN4VSs4d3l5MjVMSWJERWhoOXBFNnY1T0FZN2pDVFVQSk12
      RkFpRUE3eEVOCnRlTFJFQVFqaVMybzhndzJyLzdDT2g4ZUxkL0h0V01rMUcyS2E1WT0KLS0tLS1F
      TkQgQ0VSVElGSUNBVEUtLS0tLQoisggtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQzdU
      Q0NBcFNnQXdJQkFnSVVKN2FScDBuckRTMGJ6TlRiWmUxOWc0WUtyWmN3Q2dZSUtvWkl6ajBFQXdJ
      dwpXakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3
      R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZERZWEp5YVdWeU1SY3dGUVlEVlFRRERBNWpZUzVqWVhK
      eWFXVnlMVzVsZERBZUZ3MHkKTWpBM01qRXdNakkxTURCYUZ3MHlNekEzTWpFd01qTXdNREJhTUhn
      eEN6QUpCZ05WQkFZVEFrZENNUnN3R1FZRApWUVFIRXhJMU1TNDFNQzh0TUM0eE15OU1iMjVrYjI0
      eEVEQU9CZ05WQkFvVEIwTmhjbkpwWlhJeEhqQU1CZ05WCkJBc1RCV0ZrYldsdU1BNEdBMVVFQ3hN
      SFkyRnljbWxsY2pFYU1CZ0dBMVVFQXd3UlFXUnRhVzVBWTJGeWNtbGwKY2kxdVpYUXdXVEFUQmdj
      cWhrak9QUUlCQmdncWhrak9QUU1CQndOQ0FBUU1CYXJ3aGpheUxITVZlbHcwMkxBbAplOWNod0c0
      OC9lNllkL09rZS9leVFybVNQamhNS1NnanlHb0Z4MXp2SVlpZUI0WWZReUJzWE1GSEpOK2ZQZ2hT
      Cm80SUJHRENDQVJRd0RnWURWUjBQQVFIL0JBUURBZ2VBTUF3R0ExVWRFd0VCL3dRQ01BQXdIUVlE
      VlIwT0JCWUUKRklmclJrZXhQM05EeFVTK0RhZUtGSWVxaE5mZE1COEdBMVVkSXdRWU1CYUFGQ3I1
      WWRYZmZmZGVyWm5UY3djcgowc29mZloyK01DUUdBMVVkRVFRZE1CdUNHV05oTFhSdmIyeHpMVFZt
      T0Roa05UVm1PVGN0YzNCaWNtTXdnWTBHCkNDb0RCQVVHQndnQkJJR0FleUpoZEhSeWN5STZleUpo
      WW1GakxtbHVhWFFpT2lKMGNuVmxJaXdpWVdSdGFXNGkKT2lKMGNuVmxJaXdpYUdZdVFXWm1hV3hw
      WVhScGIyNGlPaUpqWVhKeWFXVnlJaXdpYUdZdVJXNXliMnhzYldWdQpkRWxFSWpvaVFXUnRhVzVB
      WTJGeWNtbGxjaTF1WlhRaUxDSm9aaTVVZVhCbElqb2lZV1J0YVc0aWZYMHdDZ1lJCktvWkl6ajBF
      QXdJRFJ3QXdSQUlnUkhuUS9jcytWczQreTI4NThBV2V1eVNGTXdsNGpWaUlMUjBFUnRaK3E3UUMK
      SUdwcmthRG1wVmxiVDg4amExVXlPYktmVFVFa1cyd0M2QWI4V1lCaWxWQ1AKLS0tLS1FTkQgQ0VS
      VElGSUNBVEUtLS0tLQpCDgoEU0hBMhIGU0hBMjU2SukFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0t
      LS0tCk1JSUIrVENDQVo2Z0F3SUJBZ0lVVlJYaDMwS1BiMG12RDNtZSsvKy9sVmhUQStRd0NnWUlL
      b1pJemowRUF3SXcKV2pFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBN
      QTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWREWVhKeWFXVnlNUmN3RlFZRFZRUURE
      QTVqWVM1allYSnlhV1Z5TFc1bGREQWVGdzB5Ck1qQTNNakV3TWpFNU1qWmFGdzB5TlRBMU1UQXdN
      akU1TWpaYU1Gb3hDekFKQmdOVkJBWVRBa2RDTVE4d0RRWUQKVlFRSURBWk1iMjVrYjI0eER6QU5C
      Z05WQkFjTUJreHZibVJ2YmpFUU1BNEdBMVVFQ2d3SFEyRnljbWxsY2pFWApNQlVHQTFVRUF3d09Z
      MkV1WTJGeWNtbGxjaTF1WlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DCkFBVHhK
      TUljZWNJZ090cUlsNUdZM09EQytvcTlHVjgyZVRjbGo0emZqSFc1YmlaQXBaM3dJdTZZVHRYRTJE
      L24KcjY5MlFaNHo2emdER2plMVV2YXMvWHJDbzBJd1FEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01B
      NEdBMVVkRHdFQgovd1FFQXdJQnBqQWRCZ05WSFE0RUZnUVVLdmxoMWQ5OTkxNnRtZE56Qnl2U3lo
      OTluYjR3Q2dZSUtvWkl6ajBFCkF3SURTUUF3UmdJaEFPelcrdk1NU3hVKzh3eXkyNUxJYkRFaGg5
      cEU2djVPQVk3akNUVVBKTXZGQWlFQTd4RU4KdGVMUkVBUWppUzJvOGd3MnIvN0NPaDhlTGQvSHRX
      TWsxRzJLYTVZPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChoGQWRtaW5zIjMKB1JlYWRlcnMS
      KBIeCAESGhIIEgYIARICCAAaDhIMCgpjYXJyaWVyTVNQGgZBZG1pbnMiMwoHV3JpdGVycxIoEh4I
      ARIaEggSBggBEgIIABoOEgwKCmNhcnJpZXJNU1AaBkFkbWlucyI0CgZBZG1pbnMSKhIgCAESHBII
      EgYIARICCAAaEBIOCgpjYXJyaWVyTVNQEAEaBkFkbWlucyI3CgtFbmRvcnNlbWVudBIoEh4IARIa
      EggSBggBEgIIABoOEgwKCmNhcnJpZXJNU1AaBkFkbWlucyoGQWRtaW5zGkAKFUNoYW5uZWxDcmVh
      dGlvblBvbGljeRInEgwIAxIICgZBZG1pbnMaFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zKhcvQ2hh
      bm5lbC9PcmRlcmVyL0FkbWlucyItCgZBZG1pbnMSIxIICAESBBICEgAaFy9DaGFubmVsL09yZGVy
      ZXIvQWRtaW5zKhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucxpOChBPcmRlcmVyQWRkcmVzc2VzEjoS
      Hwodb3JkZXJlcjEuc3VwcGx5Y2hhaW4tbmV0OjcwNTAaFy9DaGFubmVsL09yZGVyZXIvQWRtaW5z
      GiQKDENhcGFiaWxpdGllcxIUEgoKCAoEVjJfMBIAGgZBZG1pbnMaJgoQSGFzaGluZ0FsZ29yaXRo
      bRISEggKBlNIQTI1NhoGQWRtaW5zGi0KGUJsb2NrRGF0YUhhc2hpbmdTdHJ1Y3R1cmUSEBIGCP//
      //8PGgZBZG1pbnMiIgoHUmVhZGVycxIXEg0IAxIJCgdSZWFkZXJzGgZBZG1pbnMiIgoHV3JpdGVy
      cxIXEg0IAxIJCgdXcml0ZXJzGgZBZG1pbnMiIgoGQWRtaW5zEhgSDggDEgoKBkFkbWlucxACGgZB
      ZG1pbnMqBkFkbWlucxoOCgQKAgoACgAKAAoACgA=

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
