apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: supplychain-orderer1
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: supplychain-orderer1
  chart:
    git: git@github.com:johnhomantaring/bevel.git
    ref: local
    path: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: supplychain-net
      images:
        orderer: hyperledger/fabric-orderer:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    annotations:  
      service:
        - example1: example2
      pvc:
      deployment:
    orderer:
      name: orderer1
      loglevel: info
      localmspid: supplychainMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://afa8761a6902d4eed83106ebd15d7aec-1934446345.ap-southeast-1.elb.amazonaws.com:8200
      role: vault-role
      authpath: devsupplychain-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/supplychain-net/orderers/orderer1.supplychain-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: develop.local.com

    genesis: |-
      CiIaIF9Omeh5qHVr0PQb0DrMPf8hn7ZiznrXz6sAC7vGdAAGEpZeCpNeCpBeCngKWggBEAEaBgiR
      7+SWBiIKc3lzY2hhbm5lbCpAMzQ2YjZiMzg0MDlmZmRiYzg2MzMyZjRmMjUyMDY2ZTM3ZmJiN2Jj
      YTZjZDI1NzE2NDQzMzQxYjc0MWNhZjRjOBIaEhiZdsQfJ10Ck7MQHNkuYwPRWpAslAgx0ZUSk10K
      kF0SjV0SlSsKB09yZGVyZXISiSsSzhYKDnN1cHBseWNoYWluTVNQErsWGscUCgNNU1ASvxQStBQS
      sRQKDnN1cHBseWNoYWluTVNQEvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNBREND
      QWFhZ0F3SUJBZ0lVWG90S1h4YzIwMVAyZ0dlMzl6MjlwdW5SZDFFd0NnWUlLb1pJemowRUF3SXcK
      WGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndi
      SGxqYUdGcGJpMXVaWFF3CkhoY05Nakl3TnpJeE1URXdOekU0V2hjTk1qVXdOVEV3TVRFd056RTRX
      akJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhE
      QVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1NRW1OaExuTjFj
      SEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VIQTBJQUJLcUdv
      a01raVNwTmd6OWJ2dmJtV1ZPN1hRSTc4UWFlUlZQc25vYjhFQzZvRlRuNnpPSlgKYkhWV2QyaGVT
      dWc5MlRscUlRbzN0UTBUeXVNeERLclpUNVNqUWpCQU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpE
      Z1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCUWJWRlJ6WTY3NkR5WWhNdklxU3J1NUJk
      RWY2ekFLCkJnZ3Foa2pPUFFRREFnTklBREJGQWlCTjFnbHAwWFJoRm10enFhR1JiclptaVZqTlZF
      UDRXZis1Y01Bb3FIa3kKMmdJaEFOL2p0R1N4YlZjTGkzdzMyOTRWdGdxLzBURXFuelFYS3hHOGlO
      SU9vWFJPCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIqYILS0tLS1CRUdJTiBDRVJUSUZJQ0FU
      RS0tLS0tCk1JSUM0akNDQW9pZ0F3SUJBZ0lVTnhOK000TmplQjRIUXRzUDZWejJqSUZ1YU1Zd0Nn
      WUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJq
      RVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZR
      UUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nakl3TnpJeE1URXhOVEF3V2hjTk1q
      TXdOekl4TVRFeU1EQXdXakJzTVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5U
      QXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVE0dwpEQVlEVlFRTEV3
      VmhaRzFwYmpFZU1Cd0dBMVVFQXd3VlFXUnRhVzVBYzNWd2NHeDVZMmhoYVc0dGJtVjBNRmt3CkV3
      WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFbDE3QkoxMEZvdVNzMGVzZkJBSUw4WEdEMjBV
      OG5EOTgKcDBUdjEyMXo0RmJwVkFkcVlnZ3pJT3NQTUJEY21ka3hCdGc2Q1JaOUEzd1pCT2pGTFVV
      S2xLT0NBUlF3Z2dFUQpNQTRHQTFVZER3RUIvd1FFQXdJSGdEQU1CZ05WSFJNQkFmOEVBakFBTUIw
      R0ExVWREZ1FXQkJSRjJPMzFYYWwyCm83ZzVqekVaVVJoL25QaWcxVEFmQmdOVkhTTUVHREFXZ0JR
      YlZGUnpZNjc2RHlZaE12SXFTcnU1QmRFZjZ6QWsKQmdOVkhSRUVIVEFiZ2hsallTMTBiMjlzY3kw
      M05UVm1PV1ExWWpkakxXNTNjM2h4TUlHSkJnZ3FBd1FGQmdjSQpBUVI5ZXlKaGRIUnljeUk2ZXlK
      aFltRmpMbWx1YVhRaU9pSjBjblZsSWl3aVlXUnRhVzRpT2lKMGNuVmxJaXdpCmFHWXVRV1ptYVd4
      cFlYUnBiMjRpT2lJaUxDSm9aaTVGYm5KdmJHeHRaVzUwU1VRaU9pSkJaRzFwYmtCemRYQncKYkhs
      amFHRnBiaTF1WlhRaUxDSm9aaTVVZVhCbElqb2lZV1J0YVc0aWZYMHdDZ1lJS29aSXpqMEVBd0lE
      U0FBdwpSUUloQUpQTFlBaVIzclB0S3BKSm96b0poSXZtWlhVQVRiazZTSzUwNWI3VEVVZkZBaUJS
      MUtYSFRKYnBDU1llCnVmSnpCQWNtQThGbXh5V2Q1TG03VitpSnJLSEh1Zz09Ci0tLS0tRU5EIENF
      UlRJRklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1NkrxBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUt
      LS0tLQpNSUlDQURDQ0FhYWdBd0lCQWdJVVhvdEtYeGMyMDFQMmdHZTM5ejI5cHVuUmQxRXdDZ1lJ
      S29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQ
      TUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJzd0dRWURWUVFE
      REJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpJd056SXhNVEV3TnpFNFdoY05NalV3
      TlRFd01URXdOekU0V2pCZU1Rc3dDUVlEVlFRR0V3SkhRakVQCk1BMEdBMVVFQ0F3R1RHOXVaRzl1
      TVE4d0RRWURWUVFIREFaTWIyNWtiMjR4RURBT0JnTlZCQW9NQjA5eVpHVnkKWlhJeEd6QVpCZ05W
      QkFNTUVtTmhMbk4xY0hCc2VXTm9ZV2x1TFc1bGREQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxRwpTTTQ5
      QXdFSEEwSUFCS3FHb2tNa2lTcE5nejlidnZibVdWTzdYUUk3OFFhZVJWUHNub2I4RUM2b0ZUbjZ6
      T0pYCmJIVldkMmhlU3VnOTJUbHFJUW8zdFEwVHl1TXhES3JaVDVTalFqQkFNQThHQTFVZEV3RUIv
      d1FGTUFNQkFmOHcKRGdZRFZSMFBBUUgvQkFRREFnR21NQjBHQTFVZERnUVdCQlFiVkZSelk2NzZE
      eVloTXZJcVNydTVCZEVmNnpBSwpCZ2dxaGtqT1BRUURBZ05JQURCRkFpQk4xZ2xwMFhSaEZtdHpx
      YUdSYnJabWlWak5WRVA0V2YrNWNNQW9xSGt5CjJnSWhBTi9qdEdTeGJWY0xpM3czMjk0VnRncS8w
      VEVxbnpRWEt4RzhpTklPb1hSTwotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChoGQWRtaW5zIjgK
      BkFkbWlucxIuEiQIARIgEggSBggBEgIIABoUEhIKDnN1cHBseWNoYWluTVNQEAEaBkFkbWlucyI7
      CgtFbmRvcnNlbWVudBIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1p
      bnMiNwoHUmVhZGVycxIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1p
      bnMiNwoHV3JpdGVycxIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1p
      bnMqBkFkbWlucxoiCglCYXRjaFNpemUSFRILCAoQgICAMRiAgEAaBkFkbWlucxoeCgxCYXRjaFRp
      bWVvdXQSDhIECgIycxoGQWRtaW5zGh8KE0NoYW5uZWxSZXN0cmljdGlvbnMSCBoGQWRtaW5zGiQK
      DENhcGFiaWxpdGllcxIUEgoKCAoEVjJfMBIAGgZBZG1pbnMaihIKDUNvbnNlbnN1c1R5cGUS+BES
      7REKCGV0Y2RyYWZ0EuARCskRChhvcmRlcmVyMS5zdXBwbHljaGFpbi1uZXQQijca0wgtLS0tLUJF
      R0lOIENFUlRJRklDQVRFLS0tLS0KTUlJREF6Q0NBcW1nQXdJQkFnSVVBNXVSb1ZBd2NSTk85VDl0
      emFiK2x6djQ4TEl3Q2dZSUtvWkl6ajBFQXdJdwpYakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05W
      QkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZFBjbVJs
      Y21WeU1Sc3dHUVlEVlFRRERCSmpZUzV6ZFhCd2JIbGphR0ZwYmkxdVpYUXcKSGhjTk1qSXdOekl4
      TVRFeE5UQXdXaGNOTWpNd056SXhNVEV5TURBd1dqQnhNUXN3Q1FZRFZRUUdFd0pIUWpFYgpNQmtH
      QTFVRUJ4TVNOVEV1TlRBdkxUQXVNVE12VEc5dVpHOXVNUkF3RGdZRFZRUUtFd2RQY21SbGNtVnlN
      UkF3CkRnWURWUVFMRXdkdmNtUmxjbVZ5TVNFd0h3WURWUVFERXhodmNtUmxjbVZ5TVM1emRYQndi
      SGxqYUdGcGJpMXUKWlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFRY1ZkaFpi
      c2xXNEkzSndvSkw5YXh4a2h5cwpYV3EyNFNVR2phVW1GZGZ2cUlJU2dSUXJINTlkS1BZUzNpLzRK
      N1h5dzdGZ2I3UU9ELytDTko3R2loTndvNElCCk1EQ0NBU3d3RGdZRFZSMFBBUUgvQkFRREFnT29N
      QjBHQTFVZEpRUVdNQlFHQ0NzR0FRVUZCd01CQmdnckJnRUYKQlFjREFqQU1CZ05WSFJNQkFmOEVB
      akFBTUIwR0ExVWREZ1FXQkJSSHVJYytFWUhPM2NLWkxvUVBNOFAzRzVEVwpIVEFmQmdOVkhTTUVH
      REFXZ0JRYlZGUnpZNjc2RHlZaE12SXFTcnU1QmRFZjZ6QS9CZ05WSFJFRU9EQTJnaGh2CmNtUmxj
      bVZ5TVM1emRYQndiSGxqYUdGcGJpMXVaWFNDR205eVpHVnlaWEl4TG1SbGRtVnNiM0F1Ykc5allX
      d3UKWTI5dE1Hd0dDQ29EQkFVR0J3Z0JCR0I3SW1GMGRISnpJanA3SW1obUxrRm1abWxzYVdGMGFX
      OXVJam9pSWl3aQphR1l1Ulc1eWIyeHNiV1Z1ZEVsRUlqb2liM0prWlhKbGNqRXVjM1Z3Y0d4NVky
      aGhhVzR0Ym1WMElpd2lhR1l1ClZIbHdaU0k2SW05eVpHVnlaWElpZlgwd0NnWUlLb1pJemowRUF3
      SURTQUF3UlFJaEFQeVNJWDNsZlNDZ20yNWsKSCs1NjRyNUJGSC9KMDQ5czhjeFp4blpaWXE3S0Fp
      Qk9yeUhkRmNsVVZvbmpkN2hMSEVvWWlUUGFtUW1nRjhHYgpFTlM2Y3hsYk1BPT0KLS0tLS1FTkQg
      Q0VSVElGSUNBVEUtLS0tLQoi0wgtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJREF6Q0NB
      cW1nQXdJQkFnSVVBNXVSb1ZBd2NSTk85VDl0emFiK2x6djQ4TEl3Q2dZSUtvWkl6ajBFQXdJdwpY
      akVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RH
      OXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1Sc3dHUVlEVlFRRERCSmpZUzV6ZFhCd2JI
      bGphR0ZwYmkxdVpYUXcKSGhjTk1qSXdOekl4TVRFeE5UQXdXaGNOTWpNd056SXhNVEV5TURBd1dq
      QnhNUXN3Q1FZRFZRUUdFd0pIUWpFYgpNQmtHQTFVRUJ4TVNOVEV1TlRBdkxUQXVNVE12VEc5dVpH
      OXVNUkF3RGdZRFZRUUtFd2RQY21SbGNtVnlNUkF3CkRnWURWUVFMRXdkdmNtUmxjbVZ5TVNFd0h3
      WURWUVFERXhodmNtUmxjbVZ5TVM1emRYQndiSGxqYUdGcGJpMXUKWlhRd1dUQVRCZ2NxaGtqT1BR
      SUJCZ2dxaGtqT1BRTUJCd05DQUFRY1ZkaFpic2xXNEkzSndvSkw5YXh4a2h5cwpYV3EyNFNVR2ph
      VW1GZGZ2cUlJU2dSUXJINTlkS1BZUzNpLzRKN1h5dzdGZ2I3UU9ELytDTko3R2loTndvNElCCk1E
      Q0NBU3d3RGdZRFZSMFBBUUgvQkFRREFnT29NQjBHQTFVZEpRUVdNQlFHQ0NzR0FRVUZCd01CQmdn
      ckJnRUYKQlFjREFqQU1CZ05WSFJNQkFmOEVBakFBTUIwR0ExVWREZ1FXQkJSSHVJYytFWUhPM2NL
      WkxvUVBNOFAzRzVEVwpIVEFmQmdOVkhTTUVHREFXZ0JRYlZGUnpZNjc2RHlZaE12SXFTcnU1QmRF
      ZjZ6QS9CZ05WSFJFRU9EQTJnaGh2CmNtUmxjbVZ5TVM1emRYQndiSGxqYUdGcGJpMXVaWFNDR205
      eVpHVnlaWEl4TG1SbGRtVnNiM0F1Ykc5allXd3UKWTI5dE1Hd0dDQ29EQkFVR0J3Z0JCR0I3SW1G
      MGRISnpJanA3SW1obUxrRm1abWxzYVdGMGFXOXVJam9pSWl3aQphR1l1Ulc1eWIyeHNiV1Z1ZEVs
      RUlqb2liM0prWlhKbGNqRXVjM1Z3Y0d4NVkyaGhhVzR0Ym1WMElpd2lhR1l1ClZIbHdaU0k2SW05
      eVpHVnlaWElpZlgwd0NnWUlLb1pJemowRUF3SURTQUF3UlFJaEFQeVNJWDNsZlNDZ20yNWsKSCs1
      NjRyNUJGSC9KMDQ5czhjeFp4blpaWXE3S0FpQk9yeUhkRmNsVVZvbmpkN2hMSEVvWWlUUGFtUW1n
      RjhHYgpFTlM2Y3hsYk1BPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoSEgoFNTAwbXMQChgB
      IAUogICACBoGQWRtaW5zIiIKB1JlYWRlcnMSFxINCAMSCQoHUmVhZGVycxoGQWRtaW5zIiIKB1dy
      aXRlcnMSFxINCAMSCQoHV3JpdGVycxoGQWRtaW5zIiIKBkFkbWlucxIYEg4IAxIKCgZBZG1pbnMQ
      AhoGQWRtaW5zIioKD0Jsb2NrVmFsaWRhdGlvbhIXEg0IAxIJCgdXcml0ZXJzGgZBZG1pbnMqBkFk
      bWlucxKxLwoLQ29uc29ydGl1bXMSoS8S1i4KFVN1cHBseUNoYWluQ29uc29ydGl1bRK8LhKxFwoP
      bWFudWZhY3R1cmVyTVNQEp0XGqUVCgNNU1ASnRUSkhUSjxUKD21hbnVmYWN0dXJlck1TUBKBBi0t
      LS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDRERDQ0FiS2dBd0lCQWdJVU00M2pvREFXL2t6
      YldFc3ZoT2VPc1I0UTZUTXdDZ1lJS29aSXpqMEVBd0l3ClpERUxNQWtHQTFVRUJoTUNRMGd4RHpB
      TkJnTlZCQWdNQmxwMWNtbGphREVQTUEwR0ExVUVCd3dHV25WeWFXTm8KTVJVd0V3WURWUVFLREF4
      TllXNTFabUZqZEhWeVpYSXhIREFhQmdOVkJBTU1FMk5oTG0xaGJuVm1ZV04wZFhKbApjaTF1WlhR
      d0hoY05Nakl3TnpJeE1URXdPVEkwV2hjTk1qVXdOVEV3TVRFd09USTBXakJrTVFzd0NRWURWUVFH
      CkV3SkRTREVQTUEwR0ExVUVDQXdHV25WeWFXTm9NUTh3RFFZRFZRUUhEQVphZFhKcFkyZ3hGVEFU
      QmdOVkJBb00KREUxaGJuVm1ZV04wZFhKbGNqRWNNQm9HQTFVRUF3d1RZMkV1YldGdWRXWmhZM1Ix
      Y21WeUxXNWxkREJaTUJNRwpCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBQko5akk5RWdNOGdi
      UUxKUEJackhrTFZEcURDV09ZbDRSY0R2ClU2Z1FUL2VMQlhUNDZGRDVzQlZJZ3NxdUt6ays2ZHJK
      WVNuanI2YXRxSnhIKzZicy84dWpRakJBTUE4R0ExVWQKRXdFQi93UUZNQU1CQWY4d0RnWURWUjBQ
      QVFIL0JBUURBZ0dtTUIwR0ExVWREZ1FXQkJRdlhQYzBJaDN6bFVaQQpJTzZIRXNScEM0Z1hKREFL
      QmdncWhrak9QUVFEQWdOSUFEQkZBaUJURDBENkZDTlUya0tZVmlZUWZLcGRqQVR1CllqQkZPYXVT
      VDh1bDZuL3pZZ0loQU12UnJtNkI1QXpLNXJYMTZpZGJkMnVnZlliZ3MwYVgvdmZ3ZTFhR2dmRjkK
      LS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoi4wgtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0K
      TUlJREVUQ0NBcmVnQXdJQkFnSVVaZS83RFFQMjkrQzVrR1dLR3FjZXFuSTBocE13Q2dZSUtvWkl6
      ajBFQXdJdwpaREVMTUFrR0ExVUVCaE1DUTBneER6QU5CZ05WQkFnTUJscDFjbWxqYURFUE1BMEdB
      MVVFQnd3R1duVnlhV05vCk1SVXdFd1lEVlFRS0RBeE5ZVzUxWm1GamRIVnlaWEl4SERBYUJnTlZC
      QU1NRTJOaExtMWhiblZtWVdOMGRYSmwKY2kxdVpYUXdIaGNOTWpJd056SXhNVEV4TnpBd1doY05N
      ak13TnpJeE1URXlNakF3V2pDQmhqRUxNQWtHQTFVRQpCaE1DUTBneEdqQVlCZ05WQkFjVEVUUTNM
      ak00THpndU5UUXZXblZ5YVdOb01SVXdFd1lEVlFRS0V3eE5ZVzUxClptRmpkSFZ5WlhJeEl6QU1C
      Z05WQkFzVEJXRmtiV2x1TUJNR0ExVUVDeE1NYldGdWRXWmhZM1IxY21WeU1SOHcKSFFZRFZRUURE
      QlpCWkcxcGJrQnRZVzUxWm1GamRIVnlaWEl0Ym1WME1Ga3dFd1lIS29aSXpqMENBUVlJS29aSQp6
      ajBEQVFjRFFnQUVpMk5vMG1mNDI1blpNUU50UDRRbTlkbS9ZUUUwRUl2VXNkSm4vYmhRaHJEdFpv
      WjFlRHlSCmNXcEdaRWpDbXBYemVxQ1lTY1oweUtxM2RzWUJ2ZGpZM3FPQ0FTSXdnZ0VlTUE0R0Ex
      VWREd0VCL3dRRUF3SUgKZ0RBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZERnUVdCQlRBWGp0L0RQ
      cU9EQS9JQmIwQldsME1EVlExNFRBZgpCZ05WSFNNRUdEQVdnQlF2WFBjMEloM3psVVpBSU82SEVz
      UnBDNGdYSkRBa0JnTlZIUkVFSFRBYmdobGpZUzEwCmIyOXNjeTAyWkdRNU5tUm1OV0kwTFRsMFlt
      WnJNSUdYQmdncUF3UUZCZ2NJQVFTQmluc2lZWFIwY25NaU9uc2kKWVdKaFl5NXBibWwwSWpvaWRI
      SjFaU0lzSW1Ga2JXbHVJam9pZEhKMVpTSXNJbWhtTGtGbVptbHNhV0YwYVc5dQpJam9pYldGdWRX
      WmhZM1IxY21WeUlpd2lhR1l1Ulc1eWIyeHNiV1Z1ZEVsRUlqb2lRV1J0YVc1QWJXRnVkV1poClkz
      UjFjbVZ5TFc1bGRDSXNJbWhtTGxSNWNHVWlPaUpoWkcxcGJpSjlmVEFLQmdncWhrak9QUVFEQWdO
      SUFEQkYKQWlFQTlTaDFIQ3pMd2pIZ2x0a2ZPMW5kK0NobmUzZ2RMcldwQldOTWROUGwraU1DSUNi
      bDZiWHEvcVNLMEVPbgpsWWZNVzhMa1ZRd0hHWDJxdWttNWZDUGpmcmZwCi0tLS0tRU5EIENFUlRJ
      RklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1NkqBBi0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0t
      LQpNSUlDRERDQ0FiS2dBd0lCQWdJVU00M2pvREFXL2t6YldFc3ZoT2VPc1I0UTZUTXdDZ1lJS29a
      SXpqMEVBd0l3ClpERUxNQWtHQTFVRUJoTUNRMGd4RHpBTkJnTlZCQWdNQmxwMWNtbGphREVQTUEw
      R0ExVUVCd3dHV25WeWFXTm8KTVJVd0V3WURWUVFLREF4TllXNTFabUZqZEhWeVpYSXhIREFhQmdO
      VkJBTU1FMk5oTG0xaGJuVm1ZV04wZFhKbApjaTF1WlhRd0hoY05Nakl3TnpJeE1URXdPVEkwV2hj
      Tk1qVXdOVEV3TVRFd09USTBXakJrTVFzd0NRWURWUVFHCkV3SkRTREVQTUEwR0ExVUVDQXdHV25W
      eWFXTm9NUTh3RFFZRFZRUUhEQVphZFhKcFkyZ3hGVEFUQmdOVkJBb00KREUxaGJuVm1ZV04wZFhK
      bGNqRWNNQm9HQTFVRUF3d1RZMkV1YldGdWRXWmhZM1IxY21WeUxXNWxkREJaTUJNRwpCeXFHU000
      OUFnRUdDQ3FHU000OUF3RUhBMElBQko5akk5RWdNOGdiUUxKUEJackhrTFZEcURDV09ZbDRSY0R2
      ClU2Z1FUL2VMQlhUNDZGRDVzQlZJZ3NxdUt6ays2ZHJKWVNuanI2YXRxSnhIKzZicy84dWpRakJB
      TUE4R0ExVWQKRXdFQi93UUZNQU1CQWY4d0RnWURWUjBQQVFIL0JBUURBZ0dtTUIwR0ExVWREZ1FX
      QkJRdlhQYzBJaDN6bFVaQQpJTzZIRXNScEM0Z1hKREFLQmdncWhrak9QUVFEQWdOSUFEQkZBaUJU
      RDBENkZDTlUya0tZVmlZUWZLcGRqQVR1CllqQkZPYXVTVDh1bDZuL3pZZ0loQU12UnJtNkI1QXpL
      NXJYMTZpZGJkMnVnZlliZ3MwYVgvdmZ3ZTFhR2dmRjkKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0t
      LQoaBkFkbWlucyI4CgdSZWFkZXJzEi0SIwgBEh8SCBIGCAESAggAGhMSEQoPbWFudWZhY3R1cmVy
      TVNQGgZBZG1pbnMiOAoHV3JpdGVycxItEiMIARIfEggSBggBEgIIABoTEhEKD21hbnVmYWN0dXJl
      ck1TUBoGQWRtaW5zIjkKBkFkbWlucxIvEiUIARIhEggSBggBEgIIABoVEhMKD21hbnVmYWN0dXJl
      ck1TUBABGgZBZG1pbnMiPAoLRW5kb3JzZW1lbnQSLRIjCAESHxIIEgYIARICCAAaExIRCg9tYW51
      ZmFjdHVyZXJNU1AaBkFkbWlucyoGQWRtaW5zEqoWCgpjYXJyaWVyTVNQEpsWGrcUCgNNU1ASrxQS
      pBQSoRQKCmNhcnJpZXJNU1AS5QUtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQjl6Q0NB
      WjZnQXdJQkFnSVVaUkhLQndlZzZ2a1R3cFNZWTltUW9iNzV1aTB3Q2dZSUtvWkl6ajBFQXdJdwpX
      akVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RH
      OXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZERZWEp5YVdWeU1SY3dGUVlEVlFRRERBNWpZUzVqWVhKeWFX
      VnlMVzVsZERBZUZ3MHkKTWpBM01qRXhNVEV4TWpWYUZ3MHlOVEExTVRBeE1URXhNalZhTUZveEN6
      QUpCZ05WQkFZVEFrZENNUTh3RFFZRApWUVFJREFaTWIyNWtiMjR4RHpBTkJnTlZCQWNNQmt4dmJt
      UnZiakVRTUE0R0ExVUVDZ3dIUTJGeWNtbGxjakVYCk1CVUdBMVVFQXd3T1kyRXVZMkZ5Y21sbGNp
      MXVaWFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkMKQUFTVDNnNVVwTVVUOXNaeDBE
      T1NaVjVmbHpDaXVETDlNTzlwcDJleVcvQ0ZpdnVCdEtIOUhXSVZnbTl5bXl3VAowaGVxQTFELzA5
      RGdObWtjc3RBbVhHOC9vMEl3UURBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUE0R0ExVWREd0VCCi93
      UUVBd0lCcGpBZEJnTlZIUTRFRmdRVUk0d3ZlZTF0MHdERlp3Qlh6NkE0ZS84RW94a3dDZ1lJS29a
      SXpqMEUKQXdJRFJ3QXdSQUlnS1FjcXF2eXRvaVJGSnI0eVBTNlQrZFJEYmkwSXArbjV0SXVLRFFS
      MzRyVUNJSFhOV0dYdwpuUVNUUU1XcUN6QzZ0d0UxemFVekxBWnFvYTdmaWNWTG93U20KLS0tLS1F
      TkQgQ0VSVElGSUNBVEUtLS0tLQoisggtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQzdU
      Q0NBcFNnQXdJQkFnSVVKNjhYazZtVVRWU1RWdUR3MmhKOWtwcS90c2d3Q2dZSUtvWkl6ajBFQXdJ
      dwpXakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3
      R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZERZWEp5YVdWeU1SY3dGUVlEVlFRRERBNWpZUzVqWVhK
      eWFXVnlMVzVsZERBZUZ3MHkKTWpBM01qRXhNVEU1TURCYUZ3MHlNekEzTWpFeE1USTBNREJhTUhn
      eEN6QUpCZ05WQkFZVEFrZENNUnN3R1FZRApWUVFIRXhJMU1TNDFNQzh0TUM0eE15OU1iMjVrYjI0
      eEVEQU9CZ05WQkFvVEIwTmhjbkpwWlhJeEhqQU1CZ05WCkJBc1RCV0ZrYldsdU1BNEdBMVVFQ3hN
      SFkyRnljbWxsY2pFYU1CZ0dBMVVFQXd3UlFXUnRhVzVBWTJGeWNtbGwKY2kxdVpYUXdXVEFUQmdj
      cWhrak9QUUlCQmdncWhrak9QUU1CQndOQ0FBUWlnQ3kwNXU5UGl6WTlCN2FmTEIvVAppdDJ3TkVr
      bDNkZVdydTIyMUlGS2U0NlRPUlAveGF1cXJtNkxxLytxWVZIU00wTUVlL3dybjFtZ2pBd2txeWZY
      Cm80SUJHRENDQVJRd0RnWURWUjBQQVFIL0JBUURBZ2VBTUF3R0ExVWRFd0VCL3dRQ01BQXdIUVlE
      VlIwT0JCWUUKRkwxeDMwb2lPUzlpQjYyYkZRVldyZFdjWkgyVk1COEdBMVVkSXdRWU1CYUFGQ09N
      TDNudGJkTUF4V2NBVjgrZwpPSHYvQktNWk1DUUdBMVVkRVFRZE1CdUNHV05oTFhSdmIyeHpMVFZt
      T0Roa05UVm1PVGN0ZEhwNk56SXdnWTBHCkNDb0RCQVVHQndnQkJJR0FleUpoZEhSeWN5STZleUpo
      WW1GakxtbHVhWFFpT2lKMGNuVmxJaXdpWVdSdGFXNGkKT2lKMGNuVmxJaXdpYUdZdVFXWm1hV3hw
      WVhScGIyNGlPaUpqWVhKeWFXVnlJaXdpYUdZdVJXNXliMnhzYldWdQpkRWxFSWpvaVFXUnRhVzVB
      WTJGeWNtbGxjaTF1WlhRaUxDSm9aaTVVZVhCbElqb2lZV1J0YVc0aWZYMHdDZ1lJCktvWkl6ajBF
      QXdJRFJ3QXdSQUlnV0JnK01QV3Z5dTRyaXdKbDdaaGhrMzQ1NjhjRHdUVCt1UndvTTFIZlpXUUMK
      SUVDS3p1WWJXVUgwcEV5bGVZOGVqMVZ2bjZ6TzMzY3JXK2RDVDZrOEJaMEUKLS0tLS1FTkQgQ0VS
      VElGSUNBVEUtLS0tLQpCDgoEU0hBMhIGU0hBMjU2SuUFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0t
      LS0tCk1JSUI5ekNDQVo2Z0F3SUJBZ0lVWlJIS0J3ZWc2dmtUd3BTWVk5bVFvYjc1dWkwd0NnWUlL
      b1pJemowRUF3SXcKV2pFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBN
      QTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWREWVhKeWFXVnlNUmN3RlFZRFZRUURE
      QTVqWVM1allYSnlhV1Z5TFc1bGREQWVGdzB5Ck1qQTNNakV4TVRFeE1qVmFGdzB5TlRBMU1UQXhN
      VEV4TWpWYU1Gb3hDekFKQmdOVkJBWVRBa2RDTVE4d0RRWUQKVlFRSURBWk1iMjVrYjI0eER6QU5C
      Z05WQkFjTUJreHZibVJ2YmpFUU1BNEdBMVVFQ2d3SFEyRnljbWxsY2pFWApNQlVHQTFVRUF3d09Z
      MkV1WTJGeWNtbGxjaTF1WlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DCkFBU1Qz
      ZzVVcE1VVDlzWngwRE9TWlY1Zmx6Q2l1REw5TU85cHAyZXlXL0NGaXZ1QnRLSDlIV0lWZ205eW15
      d1QKMGhlcUExRC8wOURnTm1rY3N0QW1YRzgvbzBJd1FEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01B
      NEdBMVVkRHdFQgovd1FFQXdJQnBqQWRCZ05WSFE0RUZnUVVJNHd2ZWUxdDB3REZad0JYejZBNGUv
      OEVveGt3Q2dZSUtvWkl6ajBFCkF3SURSd0F3UkFJZ0tRY3Fxdnl0b2lSRkpyNHlQUzZUK2RSRGJp
      MElwK241dEl1S0RRUjM0clVDSUhYTldHWHcKblFTVFFNV3FDekM2dHdFMXphVXpMQVpxb2E3Zmlj
      Vkxvd1NtCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiNwoLRW5kb3JzZW1lbnQS
      KBIeCAESGhIIEgYIARICCAAaDhIMCgpjYXJyaWVyTVNQGgZBZG1pbnMiMwoHUmVhZGVycxIoEh4I
      ARIaEggSBggBEgIIABoOEgwKCmNhcnJpZXJNU1AaBkFkbWlucyIzCgdXcml0ZXJzEigSHggBEhoS
      CBIGCAESAggAGg4SDAoKY2Fycmllck1TUBoGQWRtaW5zIjQKBkFkbWlucxIqEiAIARIcEggSBggB
      EgIIABoQEg4KCmNhcnJpZXJNU1AQARoGQWRtaW5zKgZBZG1pbnMaQAoVQ2hhbm5lbENyZWF0aW9u
      UG9saWN5EicSDAgDEggKBkFkbWlucxoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMqFy9DaGFubmVs
      L09yZGVyZXIvQWRtaW5zIi0KBkFkbWlucxIjEggIARIEEgISABoXL0NoYW5uZWwvT3JkZXJlci9B
      ZG1pbnMqFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zGiYKEEhhc2hpbmdBbGdvcml0aG0SEhIICgZT
      SEEyNTYaBkFkbWlucxotChlCbG9ja0RhdGFIYXNoaW5nU3RydWN0dXJlEhASBgj/////DxoGQWRt
      aW5zGk4KEE9yZGVyZXJBZGRyZXNzZXMSOhIfCh1vcmRlcmVyMS5zdXBwbHljaGFpbi1uZXQ6NzA1
      MBoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMaJAoMQ2FwYWJpbGl0aWVzEhQSCgoICgRWMl8wEgAa
      BkFkbWlucyIiCgdXcml0ZXJzEhcSDQgDEgkKB1dyaXRlcnMaBkFkbWlucyIiCgZBZG1pbnMSGBIO
      CAMSCgoGQWRtaW5zEAIaBkFkbWlucyIiCgdSZWFkZXJzEhcSDQgDEgkKB1JlYWRlcnMaBkFkbWlu
      cyoGQWRtaW5zGg4KBAoCCgAKAAoACgAKAA==

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
